'use client'

import { useEffect, useRef, useState } from 'react'

export function DashboardMockup() {
  const ref = useRef<HTMLDivElement>(null)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true) },
      { threshold: 0.3 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [])

  const bars = [
    { label: 'Leadership', value: 82, color: '#1565c0' },
    { label: 'Communication', value: 74, color: '#f5a023' },
    { label: 'Analytical', value: 91, color: '#2196f3' },
    { label: 'Adaptability', value: 67, color: '#64b5f6' },
    { label: 'Team Collab', value: 88, color: '#1976d2' },
  ]

  return (
    <div
      ref={ref}
      className="relative bg-white rounded-2xl shadow-2xl overflow-hidden border"
      style={{ borderColor: 'var(--border)' }}
    >
      {/* Header bar */}
      <div className="flex items-center gap-2 px-4 py-3 border-b" style={{ borderColor: 'var(--border)', background: 'var(--sky-pale)' }}>
        <div className="w-3 h-3 rounded-full bg-red-400" />
        <div className="w-3 h-3 rounded-full bg-yellow-400" />
        <div className="w-3 h-3 rounded-full bg-green-400" />
        <span className="ml-3 text-xs font-mono text-muted">Samyak™ — Competency Report</span>
        <span className="ml-auto flex items-center gap-1 text-xs font-mono text-green-600">
          <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse inline-block" />
          Live
        </span>
      </div>

      <div className="p-5">
        {/* Score ring */}
        <div className="flex items-start gap-5 mb-5">
          <div className="flex-shrink-0 relative w-20 h-20">
            <svg viewBox="0 0 80 80" className="w-full h-full -rotate-90">
              <circle cx="40" cy="40" r="32" fill="none" stroke="#e8f2ff" strokeWidth="8" />
              <circle
                cx="40" cy="40" r="32"
                fill="none"
                stroke="#1565c0"
                strokeWidth="8"
                strokeDasharray={`${2 * Math.PI * 32}`}
                strokeDashoffset={visible ? `${2 * Math.PI * 32 * (1 - 0.81)}` : `${2 * Math.PI * 32}`}
                strokeLinecap="round"
                style={{ transition: 'stroke-dashoffset 1.2s ease-out' }}
              />
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <span className="font-display font-bold text-xl text-dark">81</span>
              <span className="font-mono text-[9px] text-muted">/ 100</span>
            </div>
          </div>
          <div>
            <p className="font-display font-semibold text-dark text-sm">Aisha Mwangi</p>
            <p className="font-mono text-xs text-muted mt-0.5">ICT Department · Senior Analyst</p>
            <div className="mt-2 flex flex-wrap gap-1">
              {['High Potential', 'Leadership Track'].map(tag => (
                <span key={tag} className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-royal/10 text-royal">{tag}</span>
              ))}
            </div>
          </div>
        </div>

        {/* Bar chart */}
        <p className="font-mono text-[10px] uppercase tracking-wider text-muted mb-3">Competency Breakdown</p>
        <div className="space-y-2">
          {bars.map((bar, i) => (
            <div key={bar.label} className="flex items-center gap-2">
              <span className="font-mono text-[10px] text-muted w-24 flex-shrink-0">{bar.label}</span>
              <div className="flex-1 h-2 rounded-full bg-sky-pale overflow-hidden">
                <div
                  className="h-full rounded-full"
                  style={{
                    background: bar.color,
                    width: visible ? `${bar.value}%` : '0%',
                    transition: `width 0.8s ease-out ${i * 0.1}s`,
                  }}
                />
              </div>
              <span className="font-mono text-[10px] font-medium w-6 text-right" style={{ color: bar.color }}>{bar.value}</span>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-4 pt-3 border-t flex items-center justify-between" style={{ borderColor: 'var(--border)' }}>
          <span className="font-mono text-[9px] text-muted">Generated by Samyak™ · IRT Adaptive</span>
          <span className="font-mono text-[9px] px-2 py-0.5 rounded bg-orange/10 text-orange">PDF Ready</span>
        </div>
      </div>
    </div>
  )
}
