import React from "react";
import {
    Brain,
    Zap,
    Target,
    BarChart3,
    Users,
    Briefcase,
    ShieldCheck,
    Globe,
    Search,
    Cloud,
    Code,
    MessageSquare,
    Video,
    Smartphone
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

export default function FeaturesPage() {
    const featureGroups = [
        {
            title: "Assessment & AI",
            features: [
                { name: "AI Question Generation", desc: "Scientific questions generated by GPT-4o based on competency indicators.", icon: Brain, status: "Active" },
                { name: "Role-Based Mapping", desc: "Direct mapping of evaluations to professional job roles and proficiency levels.", icon: Target, status: "Active" },
                { name: "AI Voice Interviews", desc: "Conversational AI that evaluates soft skills and domain knowledge.", icon: MessageSquare, status: "Future" },
                { name: "Code Testing", desc: "Real-time coding environment integrated into assessments.", icon: Code, status: "Planned" }
            ]
        },
        {
            title: "Management & Org",
            features: [
                { name: "Multi-Tenant Architecture", desc: "Dedicated spaces for departments, teams, or external clients.", icon: Users, status: "Active" },
                { name: "Department Hierarchies", desc: "Model your organization structure exactly as it exists.", icon: ShieldCheck, status: "Active" },
                { name: "White Label Branding", desc: "Customize the platform with your logo, colors, and domain.", icon: Globe, status: "Future" },
                { name: "Mobile Ready", desc: "Seamless assessment experience across desktops, tablets, and phones.", icon: Smartphone, status: "Active" }
            ]
        },
        {
            title: "Insights & Growth",
            features: [
                { name: "Real-Time Dashboard", desc: "Live monitoring of assessment progress and score distributions.", icon: BarChart3, status: "Active" },
                { name: "Skills Gap Analysis", desc: "Visual identifies where your team needs the most upskilling.", icon: Zap, status: "Active" },
                { name: "Career Planning Portal", desc: "Personalized roadmaps for individual employee growth.", icon: Briefcase, status: "Planned" },
                { name: "Custom Report Builder", desc: "Drag-and-drop your own analytics and export to PDF/CSV.", icon: Search, status: "Planned" }
            ]
        }
    ];

    return (
        <div className="pt-24 pb-20">
            <section className="py-24 bg-slate-50">
                <div className="max-w-7xl mx-auto px-6 text-center space-y-6">
                    <Badge className="bg-indigo-600 text-white font-black italic px-4 py-1 border-none shadow-lg shadow-indigo-100">PLATFORM CAPABILITIES</Badge>
                    <h1 className="text-6xl lg:text-8xl font-black text-gray-900 tracking-tighter italic">
                        The Science of <span className="text-indigo-600 font-black not-italic">Evaluation</span>.
                    </h1>
                    <p className="text-xl text-gray-500 font-medium max-w-2xl mx-auto italic">
                        A comprehensive ecosystem built to bridge the gap between academic output and industry demand.
                    </p>
                </div>
            </section>

            <section className="py-24 px-6 bg-white">
                <div className="max-w-7xl mx-auto space-y-32">
                    {featureGroups.map((group, gi) => (
                        <div key={gi} className="space-y-12">
                            <h2 className="text-3xl font-black italic tracking-tighter text-gray-900 uppercase border-l-8 border-indigo-600 pl-6">
                                {group.title}
                            </h2>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                {group.features.map((feature, fi) => (
                                    <Card key={fi} className="border-none shadow-xl rounded-[2.5rem] bg-white ring-1 ring-slate-100 group transition-all duration-500 hover:shadow-2xl">
                                        <CardContent className="p-10 flex items-start gap-8">
                                            <div className="w-16 h-16 rounded-2xl bg-indigo-50 flex items-center justify-center group-hover:bg-indigo-600 group-hover:scale-110 group-hover:rotate-3 transition-all duration-500 shrink-0">
                                                <feature.icon className="w-8 h-8 text-indigo-600 group-hover:text-white" />
                                            </div>
                                            <div className="space-y-3">
                                                <div className="flex items-center gap-4">
                                                    <h3 className="text-xl font-black italic tracking-tight text-gray-900 leading-tight">
                                                        {feature.name}
                                                    </h3>
                                                    <Badge variant="outline" className={`text-[9px] font-black uppercase tracking-widest px-2 py-0 border-none ${feature.status === "Active" ? "bg-green-50 text-green-600" : feature.status === "Planned" ? "bg-amber-50 text-amber-600" : "bg-slate-50 text-slate-400"
                                                        }`}>
                                                        {feature.status}
                                                    </Badge>
                                                </div>
                                                <p className="text-slate-500 font-medium italic text-sm leading-relaxed">
                                                    {feature.desc}
                                                </p>
                                            </div>
                                        </CardContent>
                                    </Card>
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            <section className="py-24 bg-slate-900 text-white relative overflow-hidden text-center">
                <div className="absolute inset-0 bg-indigo-600/10 -skew-y-6 translate-y-24" />
                <div className="max-w-4xl mx-auto px-6 relative z-10 space-y-10">
                    <Cloud className="w-20 h-20 text-indigo-400 mx-auto animate-pulse" />
                    <h2 className="text-4xl md:text-6xl font-black italic tracking-tighter leading-tight">
                        Built for Scale. <br /> Hosted on <span className="text-indigo-400">Carbon-Neutral</span> Cloud.
                    </h2>
                    <p className="text-slate-400 font-medium text-lg italic">
                        Whether you're assessing 10 people or 10,000, our cloud-native architecture ensures zero downtime and blistering fast response times.
                    </p>
                </div>
            </section>
        </div>
    );
}
