-- Baseline drift: schema already applied to DB; this migration is marked applied so history matches.
-- Generated by scripts/write-baseline-drift-migration.ts
-- Do not run manually on DB; use: npx prisma migrate resolve --applied 20260216000000_baseline_drift

-- CreateEnum
CREATE TYPE "public"."BatchDeliveryMode" AS ENUM ('LIVE_ONLINE', 'CLASSROOM', 'HYBRID');

-- CreateEnum
CREATE TYPE "public"."BatchTypeDisplay" AS ENUM ('WEEKDAY', 'WEEKEND', 'INTENSIVE', 'FLEXIBLE', 'SELF_PACED');

-- CreateEnum
CREATE TYPE "public"."BillingPeriod" AS ENUM ('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL');

-- CreateEnum
CREATE TYPE "public"."CategoryPrimary" AS ENUM ('IT', 'NON_IT', 'FUNCTIONAL', 'PERSONAL_DEVELOPMENT', 'INDUSTRY_SPECIFIC');

-- CreateEnum
CREATE TYPE "public"."CourseMediaType" AS ENUM ('IMAGE', 'VIDEO', 'BROCHURE', 'SAMPLE_PROJECT', 'CURRICULUM_PDF');

-- CreateEnum
CREATE TYPE "public"."CourseStatusDisplay" AS ENUM ('ACTIVE', 'INACTIVE', 'COMING_SOON', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "public"."CourseTypeDisplay" AS ENUM ('PREMADE', 'CURATED', 'CUSTOM', 'FINISHING_SCHOOL');

-- CreateEnum
CREATE TYPE "public"."CurriculumType" AS ENUM ('PROGRAM', 'DEGREE', 'SEMESTER', 'DEPARTMENT', 'SUBJECT', 'TOPIC');

-- CreateEnum
CREATE TYPE "public"."IndustryVertical" AS ENUM ('FINTECH', 'ECOMMERCE', 'HEALTHCARE', 'PHARMA', 'LOGISTICS', 'EDTECH', 'GOVERNMENT', 'DEFENCE', 'AVIATION', 'TRAVEL', 'RETAIL', 'REAL_ESTATE');

-- CreateEnum
CREATE TYPE "public"."InvoiceStatus" AS ENUM ('DRAFT', 'OPEN', 'PAID', 'VOID', 'UNCOLLECTIBLE');

-- CreateEnum
CREATE TYPE "public"."LessonType" AS ENUM ('THEORY', 'HANDS_ON', 'PROJECT', 'ASSESSMENT', 'LIVE_DEMO');

-- CreateEnum
CREATE TYPE "public"."MemberStatus" AS ENUM ('PENDING', 'ACTIVE', 'INACTIVE', 'INVITED');

-- CreateEnum
CREATE TYPE "public"."PrerequisiteType" AS ENUM ('MANDATORY', 'RECOMMENDED', 'GOOD_TO_HAVE');

-- CreateEnum
CREATE TYPE "public"."ReviewStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "public"."RoleVisibility" AS ENUM ('UNIVERSAL', 'TENANT_SPECIFIC');

-- CreateEnum
CREATE TYPE "public"."SubscriptionStatus" AS ENUM ('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', 'INACTIVE');

-- CreateEnum
CREATE TYPE "public"."SubscriptionTier" AS ENUM ('STARTER', 'GROWTH', 'BUSINESS', 'ENTERPRISE');

-- CreateEnum
CREATE TYPE "public"."SurveyStatus" AS ENUM ('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "public"."TargetAudienceDisplay" AS ENUM ('FRESHERS', 'JUNIOR', 'MID', 'SENIOR', 'LEADERSHIP', 'CAREER_SWITCHER', 'ALL_LEVELS');

-- CreateEnum
CREATE TYPE "public"."UserType" AS ENUM ('SUPER_ADMIN', 'TENANT', 'INDIVIDUAL');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "public"."ActivityStatus" ADD VALUE 'PLANNED';
ALTER TYPE "public"."ActivityStatus" ADD VALUE 'ON_HOLD';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "public"."MemberRole" ADD VALUE 'EMPLOYEE';
ALTER TYPE "public"."MemberRole" ADD VALUE 'INDIVIDUAL';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "public"."UserRole" ADD VALUE 'EMPLOYEE';
ALTER TYPE "public"."UserRole" ADD VALUE 'INDIVIDUAL';

-- AlterTable
ALTER TABLE "public"."Activity" ADD COLUMN     "code" TEXT NOT NULL DEFAULT 'PROJ001',
ADD COLUMN     "metadata" JSONB,
ADD COLUMN     "ownerId" TEXT;

-- AlterTable
ALTER TABLE "public"."ApprovalRequest" ADD COLUMN     "modificationNotes" TEXT,
ADD COLUMN     "modifiedData" JSONB,
ADD COLUMN     "originalData" JSONB;

-- AlterTable
ALTER TABLE "public"."Member" ADD COLUMN     "designation" TEXT,
ADD COLUMN     "developmentPlan" JSONB,
ADD COLUMN     "firstName" TEXT,
ADD COLUMN     "invitationAcceptedAt" TIMESTAMP(6),
ADD COLUMN     "invitationSentAt" TIMESTAMP(6),
ADD COLUMN     "invitationToken" TEXT,
ADD COLUMN     "joiningDate" TIMESTAMP(3),
ADD COLUMN     "lastName" TEXT,
ADD COLUMN     "memberCode" TEXT,
ADD COLUMN     "metadata" JSONB,
ADD COLUMN     "reportingToId" TEXT,
ADD COLUMN     "status" TEXT DEFAULT 'PENDING',
ADD COLUMN     "userId" TEXT;

-- AlterTable
ALTER TABLE "public"."OrganizationUnit" ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "public"."Role" ADD COLUMN     "approvedAt" TIMESTAMP(3),
ADD COLUMN     "approvedBy" TEXT,
ADD COLUMN     "rejectionReason" TEXT,
ADD COLUMN     "visibility" "public"."RoleVisibility" NOT NULL DEFAULT 'TENANT_SPECIFIC';

-- AlterTable
ALTER TABLE "public"."Survey" ADD COLUMN     "status" "public"."SurveyStatus" NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE "public"."Tenant" ADD COLUMN     "features" JSONB,
ADD COLUMN     "subscriptionTier" TEXT DEFAULT 'STARTER';

-- AlterTable
ALTER TABLE "public"."TenantSettings" ADD COLUMN     "city" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "district" TEXT,
ADD COLUMN     "lineOfBusiness" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "timezone" TEXT,
ADD COLUMN     "website" TEXT;

-- AlterTable
ALTER TABLE "public"."User" ADD COLUMN     "failedAttempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lockoutUntil" TIMESTAMP(3),
ADD COLUMN     "userType" TEXT DEFAULT 'TENANT';

-- CreateTable
CREATE TABLE "public"."ActivityCurriculum" (
    "id" TEXT NOT NULL,
    "activityId" TEXT NOT NULL,
    "curriculumNodeId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ActivityCurriculum_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AdminUser" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "twoFactorSecret" TEXT,
    "isActive" BOOLEAN DEFAULT true,
    "lastLoginAt" TIMESTAMP(6),
    "createdAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."CodeSubmission" (
    "id" TEXT NOT NULL,
    "challengeId" TEXT NOT NULL,
    "problemId" TEXT NOT NULL,
    "memberId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "score" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CodeSubmission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."CurriculumNode" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "type" "public"."CurriculumType" NOT NULL DEFAULT 'SUBJECT',
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "description" TEXT,
    "parentId" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CurriculumNode_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Report" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "templateId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "filters" JSONB,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3),
    "fileUrl" TEXT,
    "status" TEXT NOT NULL DEFAULT 'COMPLETED',
    "memberId" TEXT,

    CONSTRAINT "Report_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ReportSchedule" (
    "id" TEXT NOT NULL,
    "reportId" TEXT NOT NULL,
    "frequency" TEXT NOT NULL,
    "recipients" JSONB NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastRunAt" TIMESTAMP(3),
    "nextRunAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReportSchedule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ReportTemplate" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" TEXT,
    "config" JSONB NOT NULL,
    "isSystem" BOOLEAN NOT NULL DEFAULT false,
    "tenantId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReportTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ActivityCurriculum_activityId_curriculumNodeId_key" ON "public"."ActivityCurriculum"("activityId" ASC, "curriculumNodeId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "AdminUser_email_key" ON "public"."AdminUser"("email" ASC);

-- CreateIndex
CREATE INDEX "CurriculumNode_parentId_idx" ON "public"."CurriculumNode"("parentId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "CurriculumNode_tenantId_code_key" ON "public"."CurriculumNode"("tenantId" ASC, "code" ASC);

-- CreateIndex
CREATE INDEX "CurriculumNode_tenantId_idx" ON "public"."CurriculumNode"("tenantId" ASC);

-- CreateIndex
CREATE INDEX "Report_tenantId_idx" ON "public"."Report"("tenantId" ASC);

-- CreateIndex
CREATE INDEX "Report_userId_idx" ON "public"."Report"("userId" ASC);

-- CreateIndex
CREATE INDEX "ReportSchedule_reportId_idx" ON "public"."ReportSchedule"("reportId" ASC);

-- CreateIndex
CREATE INDEX "ReportTemplate_isSystem_idx" ON "public"."ReportTemplate"("isSystem" ASC);

-- CreateIndex
CREATE INDEX "ReportTemplate_tenantId_idx" ON "public"."ReportTemplate"("tenantId" ASC);

-- CreateIndex
CREATE INDEX "ActivityAssessment_assessmentModelId_idx" ON "public"."ActivityAssessment"("assessmentModelId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "Member_invitationToken_key" ON "public"."Member"("invitationToken" ASC);

-- CreateIndex
CREATE INDEX "MemberAssessment_assessmentModelId_idx" ON "public"."MemberAssessment"("assessmentModelId" ASC);

-- AddForeignKey
ALTER TABLE "public"."Activity" ADD CONSTRAINT "Activity_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "public"."Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ActivityAssessment" ADD CONSTRAINT "ActivityAssessment_assessmentModelId_fkey" FOREIGN KEY ("assessmentModelId") REFERENCES "public"."AssessmentModel"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ActivityCurriculum" ADD CONSTRAINT "ActivityCurriculum_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "public"."Activity"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ActivityCurriculum" ADD CONSTRAINT "ActivityCurriculum_curriculumNodeId_fkey" FOREIGN KEY ("curriculumNodeId") REFERENCES "public"."CurriculumNode"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."CurriculumNode" ADD CONSTRAINT "CurriculumNode_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "public"."CurriculumNode"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."CurriculumNode" ADD CONSTRAINT "CurriculumNode_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "public"."Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Member" ADD CONSTRAINT "Member_reportingToId_fkey" FOREIGN KEY ("reportingToId") REFERENCES "public"."Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."MemberAssessment" ADD CONSTRAINT "MemberAssessment_assessmentModelId_fkey" FOREIGN KEY ("assessmentModelId") REFERENCES "public"."AssessmentModel"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Report" ADD CONSTRAINT "Report_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "public"."Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Report" ADD CONSTRAINT "Report_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "public"."ReportTemplate"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Report" ADD CONSTRAINT "Report_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "public"."Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Report" ADD CONSTRAINT "Report_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ReportSchedule" ADD CONSTRAINT "ReportSchedule_reportId_fkey" FOREIGN KEY ("reportId") REFERENCES "public"."Report"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ReportTemplate" ADD CONSTRAINT "ReportTemplate_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "public"."Tenant"("id") ON DELETE SET NULL ON UPDATE CASCADE;

