/**
 * Generate drift SQL and write to baseline_drift migration.
 * Run from repo root. Requires shadow DB to exist.
 */
import 'dotenv/config';
import { execSync } from 'child_process';
import { mkdirSync, writeFileSync } from 'fs';
import path from 'path';

const migrationsDir = path.join(process.cwd(), 'prisma', 'migrations');
const baselineDir = path.join(migrationsDir, '20260216000000_baseline_drift');
const migrationFile = path.join(baselineDir, 'migration.sql');

const dbUrl = process.env.DATABASE_URL;
if (!dbUrl) throw new Error('DATABASE_URL required');
// Build shadow URL: replace database name with dbname_shadow (avoid URL parsing issues with @ in password)
const shadowUrl = dbUrl.replace(/\/([^/]+)\/?$/, (_, db) => `/${db}_shadow`);

// Run diff first (baseline_drift must not exist yet)
const cmd = `npx prisma migrate diff --from-migrations "${migrationsDir}" --to-url "${dbUrl}" --shadow-database-url "${shadowUrl}" --script`;
const sql = execSync(cmd, { encoding: 'utf8', maxBuffer: 10 * 1024 * 1024 });

mkdirSync(baselineDir, { recursive: true });

const header = `-- Baseline drift: schema already applied to DB; this migration is marked applied so history matches.
-- Generated by scripts/write-baseline-drift-migration.ts
-- Do not run manually on DB; use: npx prisma migrate resolve --applied 20260216000000_baseline_drift

`;
writeFileSync(migrationFile, header + sql, 'utf8');
console.log('Wrote', migrationFile);
